/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhuofengli_blackwhitephotos_NativeLib */

#ifndef _Included_com_zhuofengli_blackwhitephotos_NativeLib
#define _Included_com_zhuofengli_blackwhitephotos_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhuofengli_blackwhitephotos_NativeLib
 * Method:    processAndSaveFile
 * Signature: (Ljava/lang/String;IIIIILjava/lang/String;IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_zhuofengli_blackwhitephotos_NativeLib_processAndSaveFile
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint, jstring, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
